### ISSUE TITLE
failed with indexError when using test.dat

### ISSUE THREAD

**Issue by LipengKang** [GuipengLi/Dcluster#3]
Hi, Guipeng
@GuipengLi 
Nice work of Dcluster. But when I use test data to run it, the pipeline shows following error.
any advice? sorry for bother but I am really new to python.

```
Loading the file ...
Multidimensional Scaling for scatter plot...
Caculating rho and delta...
average percentage of neighbours (hard coded): 2.000000
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/Dcluster/run.py", line 21, in run
    (rho,delta,ordrho,dc,nneigh) = rhodelta(dist, xxdist, ND, N, percent = 2.0)
  File "build/bdist.linux-x86_64/egg/Dcluster/rhodelta.py", line 15, in rhodelta
    dc=sda[position]
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices
```

Thanks,
Lipeng

**Comment by SamMohel** [comment]
did you solve it ?
